"""initial

Revision ID: 1fc9db9860f5
Revises: 6abb545a389c
Create Date: 2023-03-15 15:37:10.374616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fc9db9860f5'
down_revision = '6abb545a389c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
