"""create post table

Revision ID: 280d7dffd798
Revises: a1251dc97d21
Create Date: 2023-03-15 14:29:12.889560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '280d7dffd798'
down_revision = 'a1251dc97d21'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
