"""initial

Revision ID: 6abb545a389c
Revises: 7984e50a74d4
Create Date: 2023-03-15 15:36:47.960943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6abb545a389c'
down_revision = '7984e50a74d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
