"""create user table

Revision ID: 7984e50a74d4
Revises: 280d7dffd798
Create Date: 2023-03-15 14:36:56.248396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7984e50a74d4'
down_revision = '280d7dffd798'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
