"""create user table

Revision ID: e04c95a9ccfd
Revises: 4ec83ae7c00b
Create Date: 2023-03-15 09:46:17.550735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e04c95a9ccfd'
down_revision = '4ec83ae7c00b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
